export const ROLES = {
  HR_ADMIN: 'HR_ADMIN',
  EMPLOYEE: 'EMPLOYEE'
};

export const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  LATE: 'LATE',
  HALF_DAY: 'HALF_DAY',
  ABSENT: 'ABSENT',
  ON_LEAVE: 'ON_LEAVE',
  WEEKEND: 'WEEKEND',
  HOLIDAY: 'HOLIDAY'
};

export const WORK_MODE = {
  OFFICE: 'OFFICE',
  WFH: 'WORK_FROM_HOME',
  FIELD: 'ON_FIELD'
};

export const LEAVE_TYPES = {
  CASUAL: 'CASUAL',
  SICK: 'SICK',
  ANNUAL: 'ANNUAL',
  UNPAID: 'UNPAID'
};

export const LEAVE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
};

export const DEFAULT_LEAVE_QUOTAS = {
  [LEAVE_TYPES.ANNUAL]: 15,
  [LEAVE_TYPES.CASUAL]: 10,
  [LEAVE_TYPES.SICK]: 10
};

export const SHIFT_RULES = {
  DEFAULT_START_TIME: '09:00',
  DEFAULT_END_TIME: '17:00',
  LATE_GRACE_MINUTES: 30,
  STANDARD_HOURS: 8.0,
  MIN_HALF_DAY_HOURS: 4.0,
  FULL_DAY_MIN_HOURS: 7.0,
  MAX_LATE_COUNT_BEFORE_DEDUCTION: 3
};
